times = ('Palmeiras','Flamengo','Fluminense','São Paulo','Bahia','Athletico-PR','Coritiba','Bragantino','Botafogo','Vasco','Vitória','Atlético-MG','Grêmio','Internacional','Santos','Cruzeiro','Corinthians','Mirassol','Remo','Chapecoense')
print('-='*15)
print('lista dos times do Brasileirão:',times)
print('-='*15)
print(f'Os 5 primeiros são:{times[:5]}')
print('-='*15)
print(f'Os 4 ultimos são:{times[-4:]}')
print('-='*15)
print(f'Os times em ordem alfabetica:{sorted(times)}')
print('-='*15)
print(f'O Cruzeiro está na {times.index("Cruzeiro")+1}º colocação')